name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install packages
        run: sudo apt-get install ocaml-nox menhir ocaml-dune ocaml-odoc
      - name: Build
        run: make
      - name: Test
        run: make test
      - name: Build documentation
        run: make doc
      - name: Upload website artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _build/default/_doc/_html/

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy website
        id: deployment
        uses: actions/deploy-pages@v4
