name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: sudo apt-get install ocaml-nox menhir
      - name: Build
        run: make -C src
